### PR TITLE
New features, settings, bug fixes and more!

### PR DESCRIPTION
**Pull request by Aiq0**
A had some free time (as school year is ending), so I worked a little bit on this plugin

Screenshot from new version (on Ubuntu)")

## Changes
I'm not sure, whatever I mentioned all changes, but I tried to mention all

### Syntax
* Shaders highlights with GLSL syntax (fallbacks to C if no GLSL syntax found, no longer need to edit syntax definition)
* C syntax for `ffi.cdef`
* Better syntax highlighting for numbers (now accepting LuaJIT number suffixes) and strings (now highlighting string.format patterns)
* Shebangs are now highlighted as in build in bash syntax
* Better functions scopes
* Fixed scope for `local` keyword
* Highlighting of documentation comments

### Live parser
* Live parser is also available for not yet saved files (which don't have extension yet), as now it also works for all files with LOVE syntax
* Live parser annotations are no longer flickering when you are typing and better `self.pending` handling
* Live parser now displays annotations for errors (configurable, only since Sublime Text 4, otherwise ignored)
* Live parser variants - **auto** (automatically chooses luac or luajit), **luac** (legacy), **luajit** (do not highlights number suffixes as errors) or **custom** (you can provide program, that will be executed with code written to stdin and that program can print errors to stderr in style `Line 123: Error message`)

### Completions and snippets
* Updated completions for LOVE 11.3, Lua, utf8, JIT, FFI, keywords and ldoc comments (ldoc comments requires little change in Sublime Text settings, it is mentioned in README) and removed Lua snippets for functions, which were moved to completions
* Removed some unnecessary spaces in some snippets
* Completions now contains metadata - kind and description with link to manual (new feature in Sublime Text 4)
* Completions now hide when you typed keyword like `end`, `do`, `else`, `then` or `repeat` (I hated when I typed then and pressed enter and it autocompleted some function)

### Settings
* Added settings shortcut to Command Palette
* Better settings (side by side, like sublime settings)
* Added tons of new settings

### Other
* Build systems are now configurable - you can change cmd and env + fixed not escaping quotes in path to folder in some cases
* Reworked README and updated screenshot in it to reflect new update
* Removed some Ös (for example in syntax name, because it is hard to type Ö when you type it in Command Palette and when you type O, it do not match Ö...)

### CODE REVIEW

**Comment by Aiq0** [comment]
Oh, and I can add message (with this changelog), that will be displayed when updated or installed using Package Control (see https://packagecontrol.io/docs/messaging), but I think, it only supports, if package released are based on tagged versions, not commits - this would require to change this in Package Control lists and then to tag version...

**Comment by Aiq0** [comment]
@szensk Can I change package distribution in [Package Control Channel](https://github.com/wbond/package_control_channel) to `"tags": true` (instead of `"branch": "master"` which is considered as deprecated), and change Sublime Text version to `"sublime_text": ">=3092"`, as .sublime-syntax is not supported before this version (I did not realized that, when I converted it from .tmLanguage). As then, it would be able to show messages with changelog after package is upgraded (as as I know, it requires to name messages after tag versions).
Oh, and it would require to change tag name from **v2.0** to something like **2.0.0** (because of semantic version requirement)

**Comment by szensk** [comment]
@Aiq0 I updated the release number to 2.0.0. I also submitted a pull request on the package control channel: https://github.com/wbond/package_control_channel/pull/8304
I'll let you know when merged.

**Comment by szensk** [comment]
@Aiq0 You seem to have already noticed but that was finally merged package control.

**Comment by Aiq0** [comment]
Yes, thanks :+1:

**Pull request merged**
